# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'breakpoint_Dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_breakpoint(object):
    def setupUi(self, Dialog_breakpoint):
        Dialog_breakpoint.setObjectName("Dialog_breakpoint")
        Dialog_breakpoint.resize(267, 141)
        self.gridLayout_2 = QtWidgets.QGridLayout(Dialog_breakpoint)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(Dialog_breakpoint)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(Dialog_breakpoint)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout.addWidget(self.lineEdit)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Button_ok = QtWidgets.QPushButton(Dialog_breakpoint)
        self.Button_ok.setObjectName("Button_ok")
        self.horizontalLayout.addWidget(self.Button_ok)
        self.pushButton_cancel = QtWidgets.QPushButton(Dialog_breakpoint)
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.horizontalLayout.addWidget(self.pushButton_cancel)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)

        self.retranslateUi(Dialog_breakpoint)
        self.pushButton_cancel.clicked.connect(Dialog_breakpoint.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog_breakpoint)

    def retranslateUi(self, Dialog_breakpoint):
        _translate = QtCore.QCoreApplication.translate
        Dialog_breakpoint.setWindowTitle(_translate("Dialog_breakpoint", "Dialog"))
        self.label.setText(_translate("Dialog_breakpoint", "请输入你要设置断点的地址"))
        self.Button_ok.setText(_translate("Dialog_breakpoint", "确定"))
        self.pushButton_cancel.setText(_translate("Dialog_breakpoint", " 取消"))
