# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'module_Dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_Module(object):
    def setupUi(self, Dialog_Module):
        Dialog_Module.setObjectName("Dialog_Module")
        Dialog_Module.resize(1171, 300)
        self.gridLayout = QtWidgets.QGridLayout(Dialog_Module)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(Dialog_Module)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.tableView = QtWidgets.QTableView(Dialog_Module)
        self.tableView.setObjectName("tableView")
        self.verticalLayout.addWidget(self.tableView)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)

        self.retranslateUi(Dialog_Module)
        QtCore.QMetaObject.connectSlotsByName(Dialog_Module)

    def retranslateUi(self, Dialog_Module):
        _translate = QtCore.QCoreApplication.translate
        Dialog_Module.setWindowTitle(_translate("Dialog_Module", "Dialog"))
        self.label.setText(_translate("Dialog_Module", "该进程载入的模块"))
