# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'showProcess_Dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_showProcess_Dialog(object):
    def setupUi(self, showProcess_Dialog):
        showProcess_Dialog.setObjectName("showProcess_Dialog")
        showProcess_Dialog.resize(800, 600)
        self.gridLayout = QtWidgets.QGridLayout(showProcess_Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(showProcess_Dialog)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.tableView = QtWidgets.QTableView(showProcess_Dialog)
        self.tableView.setObjectName("tableView")
        self.verticalLayout.addWidget(self.tableView)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(showProcess_Dialog)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(showProcess_Dialog)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_2.addWidget(self.lineEdit)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Button_attach = QtWidgets.QPushButton(showProcess_Dialog)
        self.Button_attach.setObjectName("Button_attach")
        self.horizontalLayout.addWidget(self.Button_attach)
        self.Button_cancel = QtWidgets.QPushButton(showProcess_Dialog)
        self.Button_cancel.setObjectName("Button_cancel")
        self.horizontalLayout.addWidget(self.Button_cancel)
        self.gridLayout.addLayout(self.horizontalLayout, 2, 0, 1, 1)

        self.retranslateUi(showProcess_Dialog)
        self.Button_cancel.clicked.connect(showProcess_Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(showProcess_Dialog)

    def retranslateUi(self, showProcess_Dialog):
        _translate = QtCore.QCoreApplication.translate
        showProcess_Dialog.setWindowTitle(_translate("showProcess_Dialog", "Dialog"))
        self.label_2.setText(_translate("showProcess_Dialog", "当前正在运行的进程"))
        self.label.setText(_translate("showProcess_Dialog", "输入你要附加的进程的PID"))
        self.Button_attach.setText(_translate("showProcess_Dialog", " 附加"))
        self.Button_cancel.setText(_translate("showProcess_Dialog", " 取消"))
