# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'transAddress_Dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_transAddress(object):
    def setupUi(self, Dialog_transAddress):
        Dialog_transAddress.setObjectName("Dialog_transAddress")
        Dialog_transAddress.resize(419, 138)
        self.gridLayout = QtWidgets.QGridLayout(Dialog_transAddress)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(Dialog_transAddress)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(Dialog_transAddress)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.lineEdit_RVA = QtWidgets.QLineEdit(Dialog_transAddress)
        self.lineEdit_RVA.setReadOnly(False)
        self.lineEdit_RVA.setObjectName("lineEdit_RVA")
        self.verticalLayout.addWidget(self.lineEdit_RVA)
        self.pushButton = QtWidgets.QPushButton(Dialog_transAddress)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.lineEdit_RAW = QtWidgets.QLineEdit(Dialog_transAddress)
        self.lineEdit_RAW.setReadOnly(True)
        self.lineEdit_RAW.setObjectName("lineEdit_RAW")
        self.verticalLayout.addWidget(self.lineEdit_RAW)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 2, 2)
        self.label_3 = QtWidgets.QLabel(Dialog_transAddress)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 1, 1, 1)

        self.retranslateUi(Dialog_transAddress)
        QtCore.QMetaObject.connectSlotsByName(Dialog_transAddress)

    def retranslateUi(self, Dialog_transAddress):
        _translate = QtCore.QCoreApplication.translate
        Dialog_transAddress.setWindowTitle(_translate("Dialog_transAddress", "Dialog"))
        self.label.setText(_translate("Dialog_transAddress", "内存偏移地址"))
        self.label_2.setText(_translate("Dialog_transAddress", "文件偏移地址"))
        self.pushButton.setText(_translate("Dialog_transAddress", " RVA->RAW"))
        self.label_3.setText(_translate("Dialog_transAddress", " "))
